In [1]:
import re
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/mastodon.csv')

In [3]:
df["text_clean"] = df['text']

### Todo texto em minúsculo

In [4]:
df["text_clean"] = df["text_clean"].str.lower()
df

,topic,text,created_at,likes,reblogs,replies,followers,text_clean
0,politics,New Unredacted Banner Installed on DOJ exterio...,2026-02-19 19:50:30.066000+00:00,0,2,0,0,new unredacted banner installed on doj exterio...
1,politics,"Verzweiflung:""parallel zu den dreiseitigen Ges...",2026-02-19 19:46:19+00:00,0,0,0,222,"verzweiflung:""parallel zu den dreiseitigen ges..."
2,politics,🚨Epstein NM Ranch DEMOLISHED after INVESTIGATI...,2026-02-19 19:45:06.010000+00:00,0,1,0,79,🚨epstein nm ranch demolished after investigati...
3,politics,‘They pushed so many lies about recycling’: th...,2026-02-19 19:43:06+00:00,0,2,0,436,‘they pushed so many lies about recycling’: th...
4,politics,Buttigieg leads 2028 presidential primary fiel...,2026-02-19 19:40:08.892000+00:00,0,2,0,79,buttigieg leads 2028 presidential primary fiel...
...,...,...,...,...,...,...,...,...
5799,sports,Short-handed Warriors earn one of their best w...,2026-03-06 07:30:03+00:00,0,0,0,921,short-handed warriors earn one of their best w...
5800,sports,Crystal Palace have some momentum again https:...,2026-03-06 07:15:02+00:00,0,0,0,921,crystal palace have some momentum again https:...
5801,sports,Why is everyone so upset about Arsenal's game ...,2026-03-06 07:10:02+00:00,0,0,0,921,why is everyone so upset about arsenal's game ...
5802,sports,Sean Dyche 'doesn't understand' Nottingham For...,2026-03-06 07:05:03+00:00,0,0,0,921,sean dyche 'doesn't understand' nottingham for...
5803,sports,Jeux Paralympiques de Milan-Cortina 2026 : la ...,2026-03-06 06:41:20.481000+00:00,0,0,0,35,jeux paralympiques de milan-cortina 2026 : la ...

### Remover hhtp

In [5]:
df["text_clean"] = df["text_clean"].apply(
    lambda x: re.sub(r"http\S+", "", x)
)

### Remover menções (@user)

In [6]:
df["text_clean"] = df["text_clean"].apply(
    lambda x: re.sub(r"@\w+", "", x)
)

### Remover hashtags

In [7]:
df["text_clean"] = df["text_clean"].str.replace("#", "", regex=False)

### Remover espaços extras

In [8]:
df["text_clean"] = df["text_clean"].apply(
    lambda x: re.sub(r"\s+", " ", x).strip()
)

In [9]:
df

,topic,text,created_at,likes,reblogs,replies,followers,text_clean
0,politics,New Unredacted Banner Installed on DOJ exterio...,2026-02-19 19:50:30.066000+00:00,0,2,0,0,new unredacted banner installed on doj exterior
1,politics,"Verzweiflung:""parallel zu den dreiseitigen Ges...",2026-02-19 19:46:19+00:00,0,0,0,222,"verzweiflung:""parallel zu den dreiseitigen ges..."
2,politics,🚨Epstein NM Ranch DEMOLISHED after INVESTIGATI...,2026-02-19 19:45:06.010000+00:00,0,1,0,79,🚨epstein nm ranch demolished after investigati...
3,politics,‘They pushed so many lies about recycling’: th...,2026-02-19 19:43:06+00:00,0,2,0,436,‘they pushed so many lies about recycling’: th...
4,politics,Buttigieg leads 2028 presidential primary fiel...,2026-02-19 19:40:08.892000+00:00,0,2,0,79,buttigieg leads 2028 presidential primary fiel...
...,...,...,...,...,...,...,...,...
5799,sports,Short-handed Warriors earn one of their best w...,2026-03-06 07:30:03+00:00,0,0,0,921,short-handed warriors earn one of their best w...
5800,sports,Crystal Palace have some momentum again https:...,2026-03-06 07:15:02+00:00,0,0,0,921,crystal palace have some momentum again victor...
5801,sports,Why is everyone so upset about Arsenal's game ...,2026-03-06 07:10:02+00:00,0,0,0,921,why is everyone so upset about arsenal's game ...
5802,sports,Sean Dyche 'doesn't understand' Nottingham For...,2026-03-06 07:05:03+00:00,0,0,0,921,sean dyche 'doesn't understand' nottingham for...
5803,sports,Jeux Paralympiques de Milan-Cortina 2026 : la ...,2026-03-06 06:41:20.481000+00:00,0,0,0,35,jeux paralympiques de milan-cortina 2026 : la ...

In [10]:
df.to_csv('../data/raw/mastodon.csv', index= False)