In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/raw/all_news.csv')
df

,title,content,description,publication date,id
0,The Legendary Lens: Giuliano Bevilacqua's Unwa...,"Giuliano Bevilacqua, an iconic figure in sport...","Giuliano Bevilacqua, an 84-year-old Italian ph...",2026-02-17T11:14:32Z,8b135b30a05d4ae4e417cf7857ff8fb2
1,India Defeat Triggers Reaction: PCB Chief Mohs...,India continued their domination over Pakistan...,Mohsin Naqvi has reportedly voiced his frustra...,2026-02-17T11:14:32Z,6a86d219ded3343cb51ab14020d38ab6
2,Pitbull calls on fans to help him break bizarr...,Miami-born star Pitbull has teamed up with BST...,Miami-born star Pitbull has teamed up with BST...,2026-02-17T11:14:21Z,fed278d6770ac806c24d3c7765bd72a4
3,She skips cleanser and uses this instead: Insi...,Indian actress and former Miss World Manushi C...,Indian actress and former Miss World Manushi C...,2026-02-17T11:13:00Z,cc9ee659e2492b316ee52034657d25f2
4,"Jesse Jackson, Civil Rights Leader, Dies at 84",The cause of Jackson’s death has not yet been ...,“Our father was a servant leader—not only to o...,2026-02-17T11:10:04Z,6080c74e5b7ec61ec52a1b48c41df2c7
5,"T20 World Cup 2026: Phillips, Ravindra outshin...",Sports 19 min ago\nThis is an AI assisted summ...,"For a brief while, when New Zealand found them...",2026-02-17T11:09:32Z,846c2c3d3a79a6d38c64e150ec803aec
6,"Ian Healy blasts Australia's T20 selectors, cl...",Ian Healy has called on Australia’s selectors ...,Ian Healy has called on Australia's selectors ...,2026-02-17T11:09:14Z,e3a9274b02d6daa7fece55cd3770baf4
7,"Cozy gamers rejoice, Pinterest is coming to Wo...",Pinterest has announced a new World of Warcraf...,The new Pinterest and World of Warcraft collab...,2026-02-17T11:08:11Z,c7892502c55a711df4c734ca9958d895
8,World’s largest electric ship hits safety mile...,The world’s largest electric vehicle (EV) is a...,"Hull 096, the world's largest electric ship, m...",2026-02-17T11:07:45Z,2ff6dd8eb2049f7081b976b2f26914b3
9,Video: Barack Obama Grabs Spotlight At 2026 NB...,The 2026 NBA All-Star Game at the Intuit Dome ...,Former US President Barack Obama went viral at...,2026-02-17T11:07:17Z,0bb64d4781e9a6212c5f46b78a846e98
10,Who Is Yuvraj Samra? Canada Teen Named After Y...,8\nCanada’s 19-year-old batter Yuvraj Samra ha...,Canada’s 19-year-old Yuvraj Samra became the y...,2026-02-17T11:05:19Z,d910c770d5db518f2fa85d8d65828a88
11,Why nation's top basketball prospect stuck wit...,Life has been a blur for Deron Rippey Jr. of l...,The wunderkind point guard made Blair Academy ...,2026-02-17T11:00:00Z,4f93ec0440360b7534e9109360da6d3b
12,Militants kill 11 Pakistani security personnel...,"By Mushtaq Ali\nPESHAWAR, Pakistan, Feb 17 (Re...","By Mushtaq AliPESHAWAR, Pakistan, Feb 17 (Reut...",2026-02-17T10:57:35Z,ff4023bed770f8f0b14c51d66bf10a7b
13,Isabeau Levito set for Olympic debut at 2026 M...,"Burlington County’s figure skating sensation, ...","Burlington County’s figure skating sensation, ...",2026-02-17T10:45:31Z,5239c96dde6c8619a98a73ba6692f427
14,Civil rights icon dead at 84,"The Rev. Jesse L. Jackson, a protege of the Re...",Present when the Rev. Martin Luther King Jr. w...,2026-02-17T10:36:03Z,396a13062f337875838b74ba6f614152
15,India Strengthens Global Economic Ties Amidst ...,India is fortifying its global economic presen...,"India's External Affairs Minister, S Jaishanka...",2026-02-17T10:32:49Z,e05dc57237c823c45245804a4105a186
16,Donald Trump Calls Cuba 'Failed Nation' Amid O...,President Donald Trump said that the United St...,"Trump urges Cuba to make a deal, citing humani...",2026-02-17T10:28:53Z,dd9e818a44915522cbdb61b9cf5ea8e1
17,Bangladesh's new chapter: BNP leader Tarique R...,A new dawn in Bangladesh’s politics unfolded o...,"In the February 12 elections, the Bangladesh N...",2026-02-17T10:26:26Z,617a9e647097b857ccc2949359e097b2
18,Tarique Rahman sworn in as Bangladesh's PM aft...,"DHAKA, Feb 17 - Bangladesh Nationalist Party l...","DHAKA, Feb 17 - Bangladesh Nationalist Party l...",2026-02-17T10:20:40Z,e4aad6cdb6f69278728feeda390e2b4b
19,Rhode Island men's basketball to face No. 21 S...,Saint Louis coach Josh Schertz is gaining nati...,The Billikens arrive at the Ryan Center on Tue...,2026-02-17T10:19:22Z,5c2a6a47245d29800e36afa26ddec2f1
20,5 Best OnePlus Phones Under Rs 35000 To Buy In...,Try these five amazing OnePlus smartphones thi...,If you are planning to upgrade your smartphone...,2026-02-17T11:14:44Z,de352f1c3abc8c6cafa1a26ac03da9a5
21,Solar Eclipse Effects On Pregnant Women: What ...,"Last Updated:February 17, 2026, 16:27 IST\nCul...",Cultural caution or scientific concern? Unders...,2026-02-17T10:57:48Z,6b2f2a277a29c73af0e165217f51b3fb
22,'Brilliant' series better than Silent Witness ...,Fans of Silent Witness are being urged to watc...,The crime drama is set at the fictional Scotti...,2026-02-17T10:44:00Z,15fd5fc00c3491cc4065fd97747e93a9
23,"Solar Eclipse 2026 Live Updates: How To Watch,...",Solar Eclipse 2026 Live: This annular solar ec...,This annular solar eclipse delivers a striking...,2026-02-17T10:39:15Z,633d6940efc2f09f6b8a279219924a97
24,"What is the difference between asteroids, come...",Space around the Sun contains far more than pl...,Science News: Space around the Sun contains fa...,2026-02-17T10:32:00Z,6f67dbb5d2863987684e421259d0c0b1
25,The Brown shooter and the MIT professor he killed,After they graduated from Instituto Superior T...,Loureiro and Valente were on the same path for...,2026-02-17T10:30:00Z,68a1fd914aa8f8701833eb607c6cbf0f
26,Grandest North India Mahashivratri Celebration...,"PNN\nNew Delhi [India], February 17: Delhi wit...","New Delhi [India], February 17: Delhi witnesse...",2026-02-17T10:26:02Z,a426a588b565bc3d8324ab44a35cdb28
27,'We Apologise': IT Minister Ashwini Vaishnaw O...,"Electronics And IT Minister of India, Ashwini ...","India's Electronics and IT Minister, Ashwini V...",2026-02-17T10:14:49Z,e43d7e2d37c0b0c1f1a8c5f59c3b5afc
28,Fatty15 Healthy Aging Gummies launch with scie...,The supplement brand Fatty15 has launched a ne...,Fatty15 launches Healthy Aging Gummies with pu...,2026-02-17T10:03:08Z,ba7913a62575c2eeabaa465be2bfce53
29,Fatty15 Healthy Aging Gummies launch with scie...,The supplement brand Fatty15 has launched a ne...,Fatty15 launches Healthy Aging Gummies with pu...,2026-02-17T10:03:08Z,347b69d5fb0d758ccca0bb3263165081
30,Delhi High Court Rejects Bail Extension for Ja...,The Delhi High Court instructed Jaideep Sengar...,The Delhi High Court advised Jaideep Sengar to...,2026-02-17T11:13:04Z,71c200f9dfd0c0cb28b982366f4361e6
31,Four Burner Theory explained: Why the viral li...,"Synopsis\nThe Four Burner Theory, trending onl...","The Four Burner Theory, trending online, sugge...",2026-02-17T11:13:00Z,9f2a6e89478bb2aeaa16e37f1b8dea33
32,NRI health insurance purchases jump 126% YoY; ...,Health insurance purchases by non-resident Ind...,The report noted the growth has been driven by...,2026-02-17T11:11:33Z,414ae9240600049791149137947b3b3d
33,Pakistan Minister Mohsin Naqvi dismisses ‘prop...,Pakistan’s Interior Minister Mohsin Naqvi said...,Pakistan's Interior Minister Mohsin Naqvi said...,2026-02-17T11:10:41Z,6a0b9755aeab17f7b794109689780ec3
34,Is your child's screen time damaging their vis...,"From online classes to gaming, children are sp...",Doctors warn that rising screen time and reduc...,2026-02-17T11:10:08Z,0db6e5234e684638429ac8d1c6d372c5
35,'Risk to life' as freezing South West weather ...,A yellow health alert has been issued in the S...,The warning has been issued by the UK Health S...,2026-02-17T11:09:45Z,c67cab9e5d670f20565f0108386ae084
36,'Risk to life' as freezing South West weather ...,A yellow health alert has been issued in the S...,The warning has been issued by the UK Health S...,2026-02-17T11:09:45Z,762b010f94db1e97f582fd2d9f427302
37,'Risk to life' as freezing South West weather ...,A yellow health alert has been issued in the S...,The warning has been issued by the UK Health S...,2026-02-17T11:09:45Z,e76f929e2ed686b9fe01c3d82d0a4a00
38,'Risk to life' as freezing South West weather ...,A yellow health alert has been issued in the S...,The warning has been issued by the UK Health S...,2026-02-17T11:09:45Z,369ae957796ceb19f56d29603bf885d2
39,'Risk to life' as freezing South West weather ...,At Reach and across our entities we and our pa...,The warning has been issued by the UK Health S...,2026-02-17T11:09:45Z,862a6e3204b24c1382d7c8d5fbee583e

In [24]:
df_final = df.drop_duplicates(subset=["publication date"])#df_final.to_csv("../data/raw/all_news.csv", index=False)

In [25]:
df_final

,title,content,description,publication date,id
0,The Legendary Lens: Giuliano Bevilacqua's Unwa...,"Giuliano Bevilacqua, an iconic figure in sport...","Giuliano Bevilacqua, an 84-year-old Italian ph...",2026-02-17T11:14:32Z,8b135b30a05d4ae4e417cf7857ff8fb2
2,Pitbull calls on fans to help him break bizarr...,Miami-born star Pitbull has teamed up with BST...,Miami-born star Pitbull has teamed up with BST...,2026-02-17T11:14:21Z,fed278d6770ac806c24d3c7765bd72a4
3,She skips cleanser and uses this instead: Insi...,Indian actress and former Miss World Manushi C...,Indian actress and former Miss World Manushi C...,2026-02-17T11:13:00Z,cc9ee659e2492b316ee52034657d25f2
4,"Jesse Jackson, Civil Rights Leader, Dies at 84",The cause of Jackson’s death has not yet been ...,“Our father was a servant leader—not only to o...,2026-02-17T11:10:04Z,6080c74e5b7ec61ec52a1b48c41df2c7
5,"T20 World Cup 2026: Phillips, Ravindra outshin...",Sports 19 min ago\nThis is an AI assisted summ...,"For a brief while, when New Zealand found them...",2026-02-17T11:09:32Z,846c2c3d3a79a6d38c64e150ec803aec
6,"Ian Healy blasts Australia's T20 selectors, cl...",Ian Healy has called on Australia’s selectors ...,Ian Healy has called on Australia's selectors ...,2026-02-17T11:09:14Z,e3a9274b02d6daa7fece55cd3770baf4
7,"Cozy gamers rejoice, Pinterest is coming to Wo...",Pinterest has announced a new World of Warcraf...,The new Pinterest and World of Warcraft collab...,2026-02-17T11:08:11Z,c7892502c55a711df4c734ca9958d895
8,World’s largest electric ship hits safety mile...,The world’s largest electric vehicle (EV) is a...,"Hull 096, the world's largest electric ship, m...",2026-02-17T11:07:45Z,2ff6dd8eb2049f7081b976b2f26914b3
9,Video: Barack Obama Grabs Spotlight At 2026 NB...,The 2026 NBA All-Star Game at the Intuit Dome ...,Former US President Barack Obama went viral at...,2026-02-17T11:07:17Z,0bb64d4781e9a6212c5f46b78a846e98
10,Who Is Yuvraj Samra? Canada Teen Named After Y...,8\nCanada’s 19-year-old batter Yuvraj Samra ha...,Canada’s 19-year-old Yuvraj Samra became the y...,2026-02-17T11:05:19Z,d910c770d5db518f2fa85d8d65828a88
11,Why nation's top basketball prospect stuck wit...,Life has been a blur for Deron Rippey Jr. of l...,The wunderkind point guard made Blair Academy ...,2026-02-17T11:00:00Z,4f93ec0440360b7534e9109360da6d3b
12,Militants kill 11 Pakistani security personnel...,"By Mushtaq Ali\nPESHAWAR, Pakistan, Feb 17 (Re...","By Mushtaq AliPESHAWAR, Pakistan, Feb 17 (Reut...",2026-02-17T10:57:35Z,ff4023bed770f8f0b14c51d66bf10a7b
13,Isabeau Levito set for Olympic debut at 2026 M...,"Burlington County’s figure skating sensation, ...","Burlington County’s figure skating sensation, ...",2026-02-17T10:45:31Z,5239c96dde6c8619a98a73ba6692f427
14,Civil rights icon dead at 84,"The Rev. Jesse L. Jackson, a protege of the Re...",Present when the Rev. Martin Luther King Jr. w...,2026-02-17T10:36:03Z,396a13062f337875838b74ba6f614152
15,India Strengthens Global Economic Ties Amidst ...,India is fortifying its global economic presen...,"India's External Affairs Minister, S Jaishanka...",2026-02-17T10:32:49Z,e05dc57237c823c45245804a4105a186
16,Donald Trump Calls Cuba 'Failed Nation' Amid O...,President Donald Trump said that the United St...,"Trump urges Cuba to make a deal, citing humani...",2026-02-17T10:28:53Z,dd9e818a44915522cbdb61b9cf5ea8e1
17,Bangladesh's new chapter: BNP leader Tarique R...,A new dawn in Bangladesh’s politics unfolded o...,"In the February 12 elections, the Bangladesh N...",2026-02-17T10:26:26Z,617a9e647097b857ccc2949359e097b2
18,Tarique Rahman sworn in as Bangladesh's PM aft...,"DHAKA, Feb 17 - Bangladesh Nationalist Party l...","DHAKA, Feb 17 - Bangladesh Nationalist Party l...",2026-02-17T10:20:40Z,e4aad6cdb6f69278728feeda390e2b4b
19,Rhode Island men's basketball to face No. 21 S...,Saint Louis coach Josh Schertz is gaining nati...,The Billikens arrive at the Ryan Center on Tue...,2026-02-17T10:19:22Z,5c2a6a47245d29800e36afa26ddec2f1
20,5 Best OnePlus Phones Under Rs 35000 To Buy In...,Try these five amazing OnePlus smartphones thi...,If you are planning to upgrade your smartphone...,2026-02-17T11:14:44Z,de352f1c3abc8c6cafa1a26ac03da9a5
21,Solar Eclipse Effects On Pregnant Women: What ...,"Last Updated:February 17, 2026, 16:27 IST\nCul...",Cultural caution or scientific concern? Unders...,2026-02-17T10:57:48Z,6b2f2a277a29c73af0e165217f51b3fb
22,'Brilliant' series better than Silent Witness ...,Fans of Silent Witness are being urged to watc...,The crime drama is set at the fictional Scotti...,2026-02-17T10:44:00Z,15fd5fc00c3491cc4065fd97747e93a9
23,"Solar Eclipse 2026 Live Updates: How To Watch,...",Solar Eclipse 2026 Live: This annular solar ec...,This annular solar eclipse delivers a striking...,2026-02-17T10:39:15Z,633d6940efc2f09f6b8a279219924a97
24,"What is the difference between asteroids, come...",Space around the Sun contains far more than pl...,Science News: Space around the Sun contains fa...,2026-02-17T10:32:00Z,6f67dbb5d2863987684e421259d0c0b1
25,The Brown shooter and the MIT professor he killed,After they graduated from Instituto Superior T...,Loureiro and Valente were on the same path for...,2026-02-17T10:30:00Z,68a1fd914aa8f8701833eb607c6cbf0f
26,Grandest North India Mahashivratri Celebration...,"PNN\nNew Delhi [India], February 17: Delhi wit...","New Delhi [India], February 17: Delhi witnesse...",2026-02-17T10:26:02Z,a426a588b565bc3d8324ab44a35cdb28
27,'We Apologise': IT Minister Ashwini Vaishnaw O...,"Electronics And IT Minister of India, Ashwini ...","India's Electronics and IT Minister, Ashwini V...",2026-02-17T10:14:49Z,e43d7e2d37c0b0c1f1a8c5f59c3b5afc
28,Fatty15 Healthy Aging Gummies launch with scie...,The supplement brand Fatty15 has launched a ne...,Fatty15 launches Healthy Aging Gummies with pu...,2026-02-17T10:03:08Z,ba7913a62575c2eeabaa465be2bfce53
30,Delhi High Court Rejects Bail Extension for Ja...,The Delhi High Court instructed Jaideep Sengar...,The Delhi High Court advised Jaideep Sengar to...,2026-02-17T11:13:04Z,71c200f9dfd0c0cb28b982366f4361e6
32,NRI health insurance purchases jump 126% YoY; ...,Health insurance purchases by non-resident Ind...,The report noted the growth has been driven by...,2026-02-17T11:11:33Z,414ae9240600049791149137947b3b3d
33,Pakistan Minister Mohsin Naqvi dismisses ‘prop...,Pakistan’s Interior Minister Mohsin Naqvi said...,Pakistan's Interior Minister Mohsin Naqvi said...,2026-02-17T11:10:41Z,6a0b9755aeab17f7b794109689780ec3
34,Is your child's screen time damaging their vis...,"From online classes to gaming, children are sp...",Doctors warn that rising screen time and reduc...,2026-02-17T11:10:08Z,0db6e5234e684638429ac8d1c6d372c5
35,'Risk to life' as freezing South West weather ...,A yellow health alert has been issued in the S...,The warning has been issued by the UK Health S...,2026-02-17T11:09:45Z,c67cab9e5d670f20565f0108386ae084